server:
  port: 7074

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/OperationDB
      
# Para conectar con el Eureka Server (Sevice Discovery)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7076/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
